steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/carbonwallet:latest', '.']
    id: 'build-image'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/carbonwallet:latest']
    id: 'push-image'
  
  # Deploy container image to Cloud Run (matching existing service config)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'carbonwallet-prod'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/carbonwallet:latest'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '160'
      - '--update-env-vars'
      - 'APP_ENV=production,APP_DEBUG=false,APP_KEY=base64:h9mEjSzE6+zkxaKeWAHvc5NO7y5/gedKTPpWy/WNhFw='
    id: 'deploy-service'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s

images:
  - 'gcr.io/${PROJECT_ID}/carbonwallet:latest'

